<a href="https://colab.research.google.com/github/Tubaeraslan/Machine_Learning/blob/main/quiz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Undergrad-Friendly Data Science Quiz — Questions Only

**Instructions:** This notebook contains only the questions (no solutions).  
Answer each question in the provided code cells. You can run all questions directly in **Google Colab**.

**Distribution:**
- 5 Python basics
- 2 Descriptive statistics
- 2 Math for data science
- 2 Linear algebra
- 9 Intro ML topics (linear regression, logistic regression, k-means, k-NN, PCA, etc.)

_Generated on 2025-11-01 06:39:35 UTC_


### Setup (run once)

In [ ]:
import numpy as np
import pandas as pd

from scipy import stats

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, r2_score, silhouette_score
from sklearn.datasets import make_classification, load_iris, make_blobs, make_moons, load_wine
from sklearn.linear_model import LinearRegression, LogisticRegression, Perceptron
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler

np.set_printoptions(suppress=True, precision=4)
rng = np.random.default_rng(1)


## Part A — Python Programming (5 questions)

### Q1 — List basics
Create a list of integers from 1 to 10. Print the first 3 and the last 2 elements.

In [ ]:
# Your code here
numbers = list(range(1,11))
print("First 3 numbers: ",numbers[0],numbers[1],numbers[2])
print("Last 2 numbers: ",numbers[9],numbers[8])

First 3 numbers:  1 2 3
Last 2 numbers:  10 9


### Q2 — Sum of evens
Using a loop or list comprehension, compute the sum of even numbers from 1 to 20.

In [ ]:
# Your code here
total = 0
for i in range(1,21):
  if i%2==0 :
    total+=i
print("Sum of even numbers:",total)

Sum of even numbers: 110


### Q3 — Function with default
Write `greet(name, lang='EN')` that prints 'Hello, <name>!' if EN and 'Merhaba, <name>!' if TR.

In [ ]:
# Your code here
def greet(name, lang='EN'):
  if lang == 'EN':
    print(f"Hello, {name}!")
  elif lang=='TR':
    print(f"Merhaba, {name}!")
  else:
    print("Languge not supported")

greet("tuba",'EN')
greet('tuba',"TR")


Hello, tuba!
Merhaba, tuba!


### Q4 — Dictionary counts
Given `text = 'data science is fun and data is useful'`, build a dict mapping each word to its count.

In [ ]:
# Your code here
text = "data science is fun and data is useful"

words=text.split()
#dictionary
word_count={}

for word in words:
  if word in word_count:
    word_count[word]+=1
  else:
    word_count[word] = 1

print(word_count)

{'data': 2, 'science': 1, 'is': 2, 'fun': 1, 'and': 1, 'useful': 1}


### Q5 — Simple NumPy array
Create a NumPy array `a = [1,2,3,4]`. Compute elementwise square and the mean.

In [ ]:
# Your code here
a = np.array([1,2,3,4])

squared = a ** 2

#ortalama
mean_value = np.mean(a)

print("Array: ",a)
print("Squared: ",squared)
print("Mean: ", mean_value)

Array:  [1 2 3 4]
Squared:  [ 1  4  9 16]
Mean:  2.5


## Part B — Descriptive Statistics (2 questions)

### Q6 — Mean/Median/Mode/Std
For `data = [1,2,2,3,4,4,4,5]`, compute mean, median, mode, and population std.

In [ ]:
# Your code here
data = np.array([1,2,2,3,4,4,4,5])

mean_value= np.mean(data)
median_value = np.median(data)
mode_value = stats.mode(data,keepdims=True).mode[0]
std_value = np.std(data)

print("Mean:", mean_value)
print("Median:", median_value)
print("Mode:", mode_value)
print("Population Std:", std_value)

Mean: 3.125
Median: 3.5
Mode: 4
Population Std: 1.2686114456365274


### Q7 — Quartiles & simple outlier rule
For `x = [10,11,12,13,14,50]`, find Q1, Q3, and IQR. Mark values greater than `Q3 + 1.5×IQR` as outliers.

In [ ]:
# Your code here
x = np.array([10,11,12,13,14,15,50])

Q1=np.percentile(x,25)
Q3=np.percentile(x,75)

IQR=Q3-Q1

upper_limit = Q3 + 1.5 *IQR

outliers = x[x > upper_limit]

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Üst sınır (Q3 + 1.5×IQR):", upper_limit)
print("Aykırı değerler:", outliers)

Q1: 11.5
Q3: 14.5
IQR: 3.0
Üst sınır (Q3 + 1.5×IQR): 19.0
Aykırı değerler: [50]


## Part C — Math for Data Science (2 questions)

### Q8 — Simple probability
A fair six-sided die is rolled once. Compute the probability of getting an even number.

In [3]:
# Olasılık hesabı: zar atıldığında çift gelme olasılığı

# Tüm olası sonuçlar
outcomes = [1, 2, 3, 4, 5, 6]

# Çift sayılar (istenen sonuçlar)
even_numbers = [x for x in outcomes if x % 2 == 0]

# Olasılık hesabı
probability = len(even_numbers) / len(outcomes)

print("Probability of getting an even number:", probability)


Probability of getting an even number: 0.5


### Q9 — Z-score
Given `x = 70`, mean = 60, std = 10, compute the z-score.

In [4]:
# Verilen değerler
x = 70
mean = 60
std = 10

# z-score hesabı
z = (x - mean) / std

print("Z-score:", z)


Z-score: 1.0


## Part D — Basic Linear Algebra (2 questions)

### Q10 — Dot product & norm
Let `u = [3,4]`, `v = [1,2]`. Compute the dot product `u·v` and the Euclidean norm of `u`.

In [6]:
import math

u = [3, 4]
v = [1, 2]

# Dot product
dot_product = u[0]*v[0] + u[1]*v[1]

# Euclidean norm of u
norm_u = math.sqrt(u[0]**2 + u[1]**2)

print("Dot product (u·v):", dot_product)
print("Norm of u:", norm_u)


Dot product (u·v): 11
Norm of u: 5.0


### Q11 — Solve a 2×2 system
Solve `A x = b` for `x` where `A = [[2,1],[1,3]]` and `b = [5,7]`.

In [7]:
import numpy as np

A = np.array([[2, 1],
              [1, 3]])

b = np.array([5, 7])

# Solve A x = b
x = np.linalg.solve(A, b)

print("Solution x:", x)


Solution x: [1.6 1.8]


## Part E — Intro ML (9 questions)

### Q12 — Linear regression (tiny)
Generate 50 points: `y = 2x + 1 + noise` with `x ~ U[0,5]`, noise ~ N(0,0.5). Fit `LinearRegression` and print slope, intercept.

In [9]:
from sklearn.linear_model import LinearRegression

# 1. Random seed for reproducibility
np.random.seed(0)

# 2. Generate data
x = np.random.uniform(0, 5, 50)          # 50 points uniformly between 0 and 5
noise = np.random.normal(0, 0.5, 50)     # Gaussian noise with mean 0, std 0.5
y = 2 * x + 1 + noise                    # y = 2x + 1 + noise

# 3. Reshape x for sklearn
x = x.reshape(-1, 1)

# 4. Fit Linear Regression
model = LinearRegression()
model.fit(x, y)

# 5. Print results
print("Slope (coefficient):", model.coef_[0])
print("Intercept:", model.intercept_)


Slope (coefficient): 1.9692732947309528
Intercept: 0.9963949579348599


### Q13 — Linear regression R²
Using the model from Q12, compute and print the R² score.

In [10]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

# 1. Random seed for reproducibility
np.random.seed(0)

# 2. Generate data
x = np.random.uniform(0, 5, 50)
noise = np.random.normal(0, 0.5, 50)
y = 2 * x + 1 + noise
x = x.reshape(-1, 1)

# 3. Fit Linear Regression
model = LinearRegression()
model.fit(x, y)

# 4. Predict y values
y_pred = model.predict(x)

# 5. Compute R² score
r2 = r2_score(y, y_pred)
print("R² score:", r2)


R² score: 0.9710998784919246


### Q14 — Logistic regression (easy)
Create a simple binary dataset with `make_moons(n_samples=400, noise=0.2)`. Train/test split 80/20. Fit `LogisticRegression` and print accuracy.

In [11]:
from sklearn.datasets import make_moons
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# 1. Create binary dataset (two interleaving moons)
X, y = make_moons(n_samples=400, noise=0.2, random_state=0)

# 2. Split into training (80%) and test (20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# 3. Fit Logistic Regression model
model = LogisticRegression()
model.fit(X_train, y_train)

# 4. Predict on test data
y_pred = model.predict(X_test)

# 5. Compute accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)


Accuracy: 0.925


### Q15 — k-NN (Iris)
Load Iris. Split 80/20. Fit `KNeighborsClassifier(n_neighbors=3)` and print accuracy.

In [13]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# 1. Iris veri setini yükle
iris = load_iris()
X, y = iris.data, iris.target

# 2. Train/test ayırımı (%80 - %20)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# 3. k-NN modelini oluştur (k=3)
model = KNeighborsClassifier(n_neighbors=3)
model.fit(X_train, y_train)

# 4. Tahmin yap
y_pred = model.predict(X_test)

# 5. Doğruluk hesapla
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)


Accuracy: 0.9666666666666667


### Q16 — Confusion matrix (Iris + k-NN)
Using the model from Q15, print the confusion matrix.

In [14]:
from sklearn.metrics import confusion_matrix
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

# 1. Iris veri setini yükle
iris = load_iris()
X, y = iris.data, iris.target

# 2. Train/test ayırımı (%80 - %20)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# 3. k-NN modelini oluştur ve eğit (k=3)
model = KNeighborsClassifier(n_neighbors=3)
model.fit(X_train, y_train)

# 4. Tahmin yap
y_pred = model.predict(X_test)

# 5. Confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)


Confusion Matrix:
 [[11  0  0]
 [ 0 12  1]
 [ 0  0  6]]


### Q17 — Decision Tree (easy)
On Iris, fit a small `DecisionTreeClassifier(max_depth=3)` and print test accuracy.

In [15]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# 1. Iris veri setini yükle
iris = load_iris()
X, y = iris.data, iris.target

# 2. Train/test ayırımı (%80 - %20)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# 3. Decision Tree modeli oluştur (max_depth=3)
model = DecisionTreeClassifier(max_depth=3, random_state=0)
model.fit(X_train, y_train)

# 4. Tahmin yap
y_pred = model.predict(X_test)

# 5. Test doğruluğu
accuracy = accuracy_score(y_test, y_pred)
print("Test Accuracy:", accuracy)


Test Accuracy: 0.9666666666666667


### Q18 — Naive Bayes (Iris)
Train `GaussianNB` on Iris with an 80/20 split. Print accuracy.

In [16]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

# 1. Iris veri setini yükle
iris = load_iris()
X, y = iris.data, iris.target

# 2. Train/test ayırımı (%80 - %20)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# 3. Gaussian Naive Bayes modeli oluştur ve eğit
model = GaussianNB()
model.fit(X_train, y_train)

# 4. Tahmin yap
y_pred = model.predict(X_test)

# 5. Test doğruluğu
accuracy = accuracy_score(y_test, y_pred)
print("Test Accuracy:", accuracy)


Test Accuracy: 0.9666666666666667


### Q19 — k-Means (blobs)
Generate 3 clusters with `make_blobs(n_samples=300)`. Fit `KMeans(n_clusters=3)` and print inertia.

In [17]:
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans

# 1. Veriyi oluştur (3 küme)
X, y_true = make_blobs(n_samples=300, centers=3, random_state=0)

# 2. k-Means modeli oluştur ve eğit
kmeans = KMeans(n_clusters=3, random_state=0)
kmeans.fit(X)

# 3. Inertia (küme içi toplam kareler)
print("Inertia:", kmeans.inertia_)


Inertia: 536.3679419960303


### Q20 — Simple Neural Network (MLP)
Use `make_moons(n_samples=400, noise=0.25)`. Split 75/25, fit `MLPClassifier(hidden_layer_sizes=(8,))` and print train/test accuracies.

In [18]:
from sklearn.datasets import make_moons
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score

# 1. Veri setini oluştur
X, y = make_moons(n_samples=400, noise=0.25, random_state=0)

# 2. Train/test split (%75 - %25)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

# 3. Basit MLP modeli oluştur (1 gizli katman, 8 nöron)
mlp = MLPClassifier(hidden_layer_sizes=(8,), max_iter=1000, random_state=0)
mlp.fit(X_train, y_train)

# 4. Train/test tahminleri
y_train_pred = mlp.predict(X_train)
y_test_pred = mlp.predict(X_test)

# 5. Doğruluk hesapla
train_acc = accuracy_score(y_train, y_train_pred)
test_acc = accuracy_score(y_test, y_test_pred)

print("Train Accuracy:", train_acc)
print("Test Accuracy:", test_acc)


Train Accuracy: 0.86
Test Accuracy: 0.89


---
### End of Quiz
Save and submit your Colab notebook after completing all questions.